name: Bug Report
description: Report a reproducible issue in Xpress++
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What went wrong? Give as much detail as possible.
      placeholder: A clear explanation of the issue.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
