name: Feature Request
description: Suggest a new feature for Xpress++
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: Feature Description

  - type: textarea
    id: reason
    attributes:
      label: Why is this needed?
